/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos Nuila
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        Conexion con = new Conexion(false, "postgredb.ccet05tt3mp2.us-east-1.rds.amazonaws.com", "proyecto", "5432", "postgres", "12345678");
        con.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jt_ndbO = new javax.swing.JTextField();
        jt_portO = new javax.swing.JTextField();
        jt_userO = new javax.swing.JTextField();
        jt_psswdO = new javax.swing.JTextField();
        jt_nInstanciaO = new javax.swing.JTextField();
        jb_probarO = new javax.swing.JButton();
        jl_conexionEstadoO = new javax.swing.JLabel();
        jb_probarD = new javax.swing.JButton();
        jl_conexionEstadoO1 = new javax.swing.JLabel();
        jt_psswdD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt_userD = new javax.swing.JTextField();
        jt_portD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jt_ndbD = new javax.swing.JTextField();
        jt_nInstanciaD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jb_guardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Configuración de Base de Datos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Base de Datos de Origen");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel3.setText("Nombre Instancia:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Nombre Base Datos:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setText("Puerto:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel6.setText("Password:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel7.setText("Nombre Usuario:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel2.add(jt_ndbO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 170, -1));
        jPanel2.add(jt_portO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 90, -1));
        jPanel2.add(jt_userO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 140, -1));
        jPanel2.add(jt_psswdO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 170, -1));
        jPanel2.add(jt_nInstanciaO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, -1));

        jb_probarO.setText("Probar");
        jPanel2.add(jb_probarO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 80, 30));

        jl_conexionEstadoO.setText("Conexion");
        jPanel2.add(jl_conexionEstadoO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 110, -1));

        jb_probarD.setText("Probar");
        jPanel2.add(jb_probarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 80, 30));

        jl_conexionEstadoO1.setText("Conexion");
        jPanel2.add(jl_conexionEstadoO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 110, -1));
        jPanel2.add(jt_psswdD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 170, -1));

        jLabel8.setText("Password:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jLabel9.setText("Nombre Usuario:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));
        jPanel2.add(jt_userD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 140, -1));
        jPanel2.add(jt_portD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 90, -1));

        jLabel10.setText("Puerto:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel11.setText("Nombre Base Datos:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));
        jPanel2.add(jt_ndbD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 170, -1));
        jPanel2.add(jt_nInstanciaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 170, -1));

        jLabel12.setText("Nombre Instancia:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Base de Datos de Destino");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jb_guardar.setText("Guardar");
        jPanel2.add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jTabbedPane1.addTab("Configuración", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Replicación", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_probarD;
    private javax.swing.JButton jb_probarO;
    private javax.swing.JLabel jl_conexionEstadoO;
    private javax.swing.JLabel jl_conexionEstadoO1;
    private javax.swing.JTextField jt_nInstanciaD;
    private javax.swing.JTextField jt_nInstanciaO;
    private javax.swing.JTextField jt_ndbD;
    private javax.swing.JTextField jt_ndbO;
    private javax.swing.JTextField jt_portD;
    private javax.swing.JTextField jt_portO;
    private javax.swing.JTextField jt_psswdD;
    private javax.swing.JTextField jt_psswdO;
    private javax.swing.JTextField jt_userD;
    private javax.swing.JTextField jt_userO;
    // End of variables declaration//GEN-END:variables
}
